name: Tag with short sha
on:
  workflow_dispatch:
  push:
    branch: main
    paths-ignore:
      - '.github/**'

concurrency:
  group: ${{ github.ref }}/tag
  cancel-in-progress: true

jobs:
  create-tag:
    runs-on: self-hosted
    permissions:
      deployments: write
      packages: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
      - name: Set outputs
        id: short_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.short_sha.outputs.sha_short }}
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ steps.short_sha.outputs.sha_short }}"
          message: "${{ steps.short_sha.outputs.sha_short }} release"